### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by Sanabria** [omelhus/wp-pk-fixer#1]
Hi, thank you for creating this plugin. I'm exactly in the same situation where DO is asking me to fix tables without primary keys (such as Yoasts). 

I already installed it but I'm not sure exactly how the plugin is intended to work. Do I need to do something else? Will it run on its own and add the primary keys to tables that don't have them? Thanks in advance.

**Comment by omelhus** [comment]
Hey,

Just have the plugin activated when you install Yoast or others and it will hook into the query that creates the tables and add the primary key fields automatically.

If you already have the tables you’ll have to add the primary keys manually.

Cheers!
